const PDFDocument = require('pdfkit');

function formatMoney(value) {
  return Number(value || 0).toFixed(2);
}

function formatPercent(value) {
  return `${Number(value || 0).toFixed(1)}%`;
}

function buildBusinessReportPdfBuffer({ business, summary, loanReadiness }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const fromLabel = new Date(summary.from).toLocaleDateString('en-GB');
    const toLabel = new Date(summary.to).toLocaleDateString('en-GB');

    doc.fontSize(22).fillColor('#0f172a').text(business?.name || 'BizManager Business Report', 48, 48);
    doc.fontSize(10).fillColor('#64748b');
    if (business?.phone) doc.text(`Phone: ${business.phone}`, 48, 76);
    doc.text(`Period: ${fromLabel} to ${toLabel}`, 48, 92);

    let y = 130;
    const rows = [
      ['Sales (Revenue)', `GHS ${formatMoney(summary.revenue)}`],
      ['Cash collected', `GHS ${formatMoney(summary.cash_collected)}`],
      ['Customers owing', `GHS ${formatMoney(summary.credit_outstanding)}`],
      ['Cost of goods', `GHS ${formatMoney(summary.cost_of_goods_sold)}`],
      ['Gross profit', `GHS ${formatMoney(summary.gross_profit)}`],
      ['Gross margin', formatPercent(summary.gross_margin)],
      ['Expenses', `GHS ${formatMoney(summary.expenses)}`],
      ['Net profit', `GHS ${formatMoney(summary.net_profit)}`],
      ['Net margin', formatPercent(summary.net_margin)],
      ['Stock value', `GHS ${formatMoney(summary.stock_value)}`],
    ];

    doc.fontSize(12).fillColor('#0f172a').text('Business Performance', 48, y);
    y += 22;
    doc.fontSize(10).fillColor('#475569');

    for (const [label, value] of rows) {
      doc.text(label, 48, y, { width: 260 });
      doc.text(value, 320, y, { width: 227, align: 'right' });
      y += 18;
    }

    y += 10;
    doc.fontSize(12).fillColor('#0f172a').text('Top Products', 48, y);
    y += 20;
    doc.fontSize(10).fillColor('#475569');

    if ((summary.top_products || []).length === 0) {
      doc.text('No product sales in this period.', 48, y);
      y += 18;
    } else {
      for (const product of summary.top_products.slice(0, 8)) {
        doc.text(`${product.name} (${product.qty} sold)`, 48, y, { width: 320 });
        doc.text(`GHS ${formatMoney(product.revenue)}`, 320, y, { width: 227, align: 'right' });
        y += 16;
      }
    }

    y += 10;
    doc.fontSize(12).fillColor('#0f172a').text('Low Stock', 48, y);
    y += 20;
    doc.fontSize(10).fillColor('#475569');

    if ((summary.low_stock || []).length === 0) {
      doc.text('No low-stock alerts.', 48, y);
      y += 18;
    } else {
      for (const item of summary.low_stock.slice(0, 8)) {
        doc.text(`${item.name}: ${item.stock_qty} left`, 48, y);
        y += 16;
      }
    }

    if (loanReadiness) {
      y += 12;
      doc.fontSize(12).fillColor('#0f172a').text('Loan Readiness Estimate', 48, y);
      y += 20;
      doc.fontSize(10).fillColor('#475569');
      doc.text(`Score: ${loanReadiness.score}/100 (${loanReadiness.grade})`, 48, y);
      y += 16;
      doc.text(`Estimated safe monthly repayment: GHS ${formatMoney(loanReadiness.estimated_safe_monthly_repayment)}`, 48, y);
      y += 24;
      doc.fontSize(9).fillColor('#94a3b8').text(loanReadiness.disclaimer, 48, y, { width: 499 });
    }

    doc.fontSize(9).fillColor('#94a3b8').text('Generated by BizManager', 48, 760, {
      width: 499,
      align: 'center',
    });

    doc.end();
  });
}

module.exports = {
  buildBusinessReportPdfBuffer,
};
