const PDFDocument = require('pdfkit');
const axios = require('axios');

function formatMoney(value) {
  return Number(value || 0).toFixed(2);
}

function buildInvoicePdfBuffer({ business, invoice }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(22).fillColor('#0f172a').text(business?.name || 'BizManager Invoice', 48, 48);
    doc.fontSize(10).fillColor('#64748b');

    if (business?.phone) {
      doc.text(`Phone: ${business.phone}`, 48, 76);
    }

    doc.text(`Invoice: ${invoice.invoice_number}`, 48, 102);
    doc.text(`Status: ${invoice.status}`, 48, 118);
    doc.text(`Created: ${new Date(invoice.created_at).toLocaleDateString('en-GB')}`, 48, 134);
    if (invoice.due_date) {
      doc.text(`Due: ${new Date(invoice.due_date).toLocaleDateString('en-GB')}`, 48, 150);
    }

    doc.fontSize(12).fillColor('#0f172a').text('Bill To', 48, 186);
    doc.fontSize(10).fillColor('#475569');
    doc.text(invoice.customer_name || 'Customer not provided', 48, 204);
    if (invoice.customer_phone) {
      doc.text(invoice.customer_phone, 48, 220);
    }
    if (invoice.customer_email) {
      doc.text(invoice.customer_email, 48, 236);
    }

    const startY = 286;
    doc.moveTo(48, startY - 12).lineTo(547, startY - 12).strokeColor('#cbd5e1').stroke();
    doc.fontSize(10).fillColor('#0f172a').text('Item', 48, startY);
    doc.text('Qty', 332, startY, { width: 50, align: 'right' });
    doc.text('Price', 392, startY, { width: 65, align: 'right' });
    doc.text('Subtotal', 467, startY, { width: 80, align: 'right' });
    doc.moveTo(48, startY + 16).lineTo(547, startY + 16).strokeColor('#cbd5e1').stroke();

    let cursorY = startY + 28;
    for (const item of invoice.items || []) {
      doc.fillColor('#0f172a').text(item.name || 'Item', 48, cursorY, { width: 270 });
      doc.text(String(item.quantity || 0), 332, cursorY, { width: 50, align: 'right' });
      doc.text(`GHS ${formatMoney(item.price)}`, 392, cursorY, { width: 65, align: 'right' });
      doc.text(`GHS ${formatMoney(item.subtotal)}`, 467, cursorY, { width: 80, align: 'right' });
      cursorY += 24;
    }

    doc.moveTo(48, cursorY + 6).lineTo(547, cursorY + 6).strokeColor('#cbd5e1').stroke();
    doc.fontSize(12).fillColor('#0f172a').text('Total', 392, cursorY + 18, { width: 65, align: 'right' });
    doc.fontSize(14).text(`GHS ${formatMoney(invoice.total)}`, 467, cursorY + 16, { width: 80, align: 'right' });

    if (invoice.note) {
      doc.fontSize(11).fillColor('#0f172a').text('Notes', 48, cursorY + 64);
      doc.fontSize(10).fillColor('#475569').text(invoice.note, 48, cursorY + 82, { width: 499 });
    }

    doc.fontSize(9).fillColor('#94a3b8').text('Generated by BizManager', 48, 760, {
      width: 499,
      align: 'center',
    });

    doc.end();
  });
}

async function sendInvoiceEmail({ invoice, pdfBuffer }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.RESEND_FROM_EMAIL;

  if (!apiKey || !from) {
    const error = new Error('Invoice email delivery is not configured. Set RESEND_API_KEY and RESEND_FROM_EMAIL.');
    error.code = 'EMAIL_CONFIG';
    throw error;
  }

  if (!invoice.customer_email) {
    const error = new Error('Customer email is required before sending an invoice.');
    error.code = 'EMAIL_RECIPIENT';
    throw error;
  }

  await axios.post('https://api.resend.com/emails', {
    from,
    to: [invoice.customer_email],
    subject: `${invoice.invoice_number} from BizManager`,
    html: `
      <div style="font-family: Arial, sans-serif; color: #0f172a; line-height: 1.5;">
        <h2 style="margin-bottom: 12px;">Your invoice is ready</h2>
        <p>Please find invoice <strong>${invoice.invoice_number}</strong> attached as a PDF.</p>
        <p>Total: <strong>GHS ${formatMoney(invoice.total)}</strong></p>
        <p>Due date: <strong>${invoice.due_date ? new Date(invoice.due_date).toLocaleDateString('en-GB') : 'Not set'}</strong></p>
        <p>Sent from BizManager.</p>
      </div>
    `,
    attachments: [
      {
        filename: `${invoice.invoice_number}.pdf`,
        content: pdfBuffer.toString('base64'),
      },
    ],
  }, {
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
  });
}

module.exports = {
  buildInvoicePdfBuffer,
  sendInvoiceEmail,
};
